[package]
name = "udcn-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
udcn-common = { path = "../udcn-common" }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "udcn-daemon"
path = "src/main.rs"

