[package]
name = "udcn-ebpf"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib"]
test = false
doctest = false


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

